name: server
description: An HTTP server for the MTG Deck Builder.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  postgres: ^3.0.0
  dotenv: ^4.0.0
  http: ^1.2.1
  collection: ^1.18.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.12.0
  json_annotation: ^4.8.0

dev_dependencies:
  test: ^1.14.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
